/*
===============================================================================
Enterprise Dynamic KPI Engine

Project
-------
Enterprise Sales Analytics Platform

Description
-----------
Dynamic KPI engine powering executive Power BI dashboards through a reusable
semantic model. A single calculation engine evaluates multiple business KPIs
across different time granularities while minimizing duplicated business logic.

Architecture
------------
Metric Selection
        │
Time Selection
        │
Dynamic Calculation Engine
        │
Semantic Model
        │
Power BI Dashboard

Capabilities
------------
• Dynamic KPI Selection
• Dynamic Time Intelligence
• Executive Scorecards
• Multi-domain KPI Calculation

Representative Metrics
----------------------
• Revenue
• Successful Orders
• Average Order Value
• Customer Service KPI
• FriendSell Traffic

Techniques
----------
• SWITCH(TRUE())
• CALCULATE()
• VAR / RETURN
• WINDOW()
• ORDERBY()
• PARTITIONBY()
• SELECTEDVALUE()

===============================================================================
*/

VAR SelectedMetric =
    SELECTEDVALUE ( MetricGroup[Metric] )

VAR SelectedTimeRange =
    SELECTEDVALUE ( 'Time Range'[Time Range] )

VAR YearWindow =
    WINDOW (
        0, ABS,
        0, REL,
        ALL ( 'dimDate' ),
        ORDERBY ( 'dimDate'[Date] ),
        PARTITIONBY ( 'dimDate'[Year] )
    )

VAR MonthWindow =
    WINDOW (
        0, ABS,
        0, REL,
        ALL ( 'dimDate' ),
        ORDERBY ( 'dimDate'[Date] ),
        PARTITIONBY ( 'dimDate'[Month & Year] )
    )

VAR WeekWindow =
    WINDOW (
        0, ABS,
        0, REL,
        ALL ( 'dimDate' ),
        ORDERBY ( 'dimDate'[Date] ),
        PARTITIONBY ( 'dimDate'[Year & Week] )
    )

RETURN

SWITCH (

    TRUE(),

    //------------------------------------------------------------------
    // Revenue
    //------------------------------------------------------------------

    SelectedMetric = "Revenue",

        SWITCH (

            SelectedTimeRange,

            "Year",
                CALCULATE ( [Revenue], YearWindow ),

            "Month",
                CALCULATE ( [Revenue], MonthWindow ),

            "Week",
                CALCULATE ( [Revenue], WeekWindow ),

            [Revenue]
        ),

    //------------------------------------------------------------------
    // Successful Orders
    //------------------------------------------------------------------

    SelectedMetric = "Orders",

        SWITCH (

            SelectedTimeRange,

            "Year",
                CALCULATE ( [Successful Orders], YearWindow ),

            "Month",
                CALCULATE ( [Successful Orders], MonthWindow ),

            "Week",
                CALCULATE ( [Successful Orders], WeekWindow ),

            [Successful Orders]
        ),

    //------------------------------------------------------------------
    // Average Order Value
    //------------------------------------------------------------------

    SelectedMetric = "Average Order Value",

        ROUND (

            CALCULATE (
                [Average Order Value],
                MonthWindow
            ),

            0

        ),

    //------------------------------------------------------------------
    // Customer Service KPI
    //------------------------------------------------------------------

    SelectedMetric = "Customer Service",

        CALCULATE (

            [Customer Service KPI],

            MonthWindow

        ),

    //------------------------------------------------------------------
    // FriendSell
    //------------------------------------------------------------------

    SelectedMetric = "FriendSell",

        CALCULATE (

            [FriendSell Traffic],

            MonthWindow

        ),

    //------------------------------------------------------------------
    // Default
    //------------------------------------------------------------------

    BLANK()

)

/*
Production Semantic Model

• 47 Tables
• 77 Relationships
• 477 Measures

This repository contains representative DAX patterns extracted from the
production semantic model. Business-specific calculations and proprietary
logic have been intentionally omitted.
*/
