"""
Customer Service Analytics Platform
-----------------------------------

Daily ETL Pipeline

This module orchestrates the execution of ETL processes used to build
customer service analytics datasets.

Production credentials, database objects, proprietary SQL, and sensitive
business logic have been removed or generalized for portfolio purposes.
"""

import logging
from datetime import date

from etl_steps import (
etl_cus_to_coor,
etl_coor_to_sup,
etl_cus_to_support,
etl_cus_to_transfer,
etl_transfer_to_support,
etl_session_waiting_duration,
etl_session_start_end,
etl_end_to_end,
etl_night_session_stats,
etl_all_steps,
)

logger = logging.getLogger(**name**)

PIPELINE_STEPS = [
("customer_to_coordinator", etl_cus_to_coor),
("coordinator_to_support", etl_coor_to_sup),
("customer_to_support", etl_cus_to_support),
("customer_to_transfer", etl_cus_to_transfer),
("transfer_to_support", etl_transfer_to_support),
("session_waiting_duration", etl_session_waiting_duration),
("session_start_end", etl_session_start_end),
("end_to_end", etl_end_to_end),
("night_session_stats", etl_night_session_stats),
("all_steps", etl_all_steps),
]

def run_daily_pipeline(run_date: date):
"""
Execute the complete daily ETL workflow.

```
ETL steps are executed sequentially because downstream datasets
depend on outputs generated by previous transformation steps.
"""

logger.info(
    "Starting Customer Service Analytics ETL for %s",
    run_date,
)

results = {}

for step_name, step_function in PIPELINE_STEPS:

    logger.info("Starting ETL step: %s", step_name)

    try:
        step_function(run_date=run_date)

        results[step_name] = "SUCCESS"

        logger.info(
            "Completed ETL step: %s",
            step_name,
        )

    except Exception:
        results[step_name] = "FAILED"

        logger.exception(
            "ETL step failed: %s",
            step_name,
        )

        raise

logger.info(
    "Customer Service Analytics ETL completed for %s",
    run_date,
)

return results
```

if **name** == "**main**":
run_daily_pipeline(date.today())
